/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */

#include "s3eExt.h"
#include "IwDebug.h"
#include "s3eDevice.h"


#include "s3eIOSiCloud.h"


// Define S3E_EXT_SKIP_LOADER_CALL_LOCK on the user-side to skip LoaderCallStart/LoaderCallDone()-entry.
// e.g. in s3eNUI this is used for generic user-side IwUI-based implementation.
#ifndef S3E_EXT_SKIP_LOADER_CALL_LOCK
#if (defined(WINAPI_FAMILY) && (WINAPI_FAMILY == WINAPI_FAMILY_PHONE_APP)) || defined I3D_ARCH_NACLX86_64
// For platforms missing stack-switching (WP8, NaCl, etc.) make loader-entry via LoaderCallStart/LoaderCallDone() on the user-side.
#define LOADER_CALL_LOCK
#endif
#endif


#include "s3eIOSiCloud_interface.h"

static s3eIOSiCloudFuncs g_Ext;
static bool g_GotExt = false;
static bool g_TriedExt = false;
static bool g_TriedNoMsgExt = false;

static bool _extLoad()
{
    if (!g_GotExt && !g_TriedExt)
    {
        s3eResult res = s3eExtGetHash(0x47c24b3b, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        else
            s3eDebugAssertShow(S3E_MESSAGE_CONTINUE_STOP_IGNORE,                 "error loading extension: s3eIOSiCloud");

        g_TriedExt = true;
        g_TriedNoMsgExt = true;
    }

    return g_GotExt;
}

static bool _extLoadNoMsg()
{
    if (!g_GotExt && !g_TriedNoMsgExt)
    {
        s3eResult res = s3eExtGetHash(0x47c24b3b, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        g_TriedNoMsgExt = true;
        if (g_TriedExt)
            g_TriedExt = true;
    }

    return g_GotExt;
}

s3eBool s3eIOSiCloudAvailable()
{
    _extLoadNoMsg();
    return g_GotExt ? S3E_TRUE : S3E_FALSE;
}

s3eResult s3eIOSiCloudRegister(s3eIOSiCloudCallback cbid, s3eCallback fn, void* userData)
{
    IwTrace(IOSICLOUD_VERBOSE, ("calling s3eIOSiCloud[0] func: s3eIOSiCloudRegister"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_s3eIOSiCloudRegister);
#endif

    s3eResult ret = g_Ext.m_s3eIOSiCloudRegister(cbid, fn, userData);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_s3eIOSiCloudRegister);
#endif

    return ret;
}

s3eResult s3eIOSiCloudUnRegister(s3eIOSiCloudCallback cbid, s3eCallback fn)
{
    IwTrace(IOSICLOUD_VERBOSE, ("calling s3eIOSiCloud[1] func: s3eIOSiCloudUnRegister"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_s3eIOSiCloudUnRegister);
#endif

    s3eResult ret = g_Ext.m_s3eIOSiCloudUnRegister(cbid, fn);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_s3eIOSiCloudUnRegister);
#endif

    return ret;
}

s3eResult s3eIOSiCloudStart(const char* fileName, s3eBool supportConflictResolution)
{
    IwTrace(IOSICLOUD_VERBOSE, ("calling s3eIOSiCloud[2] func: s3eIOSiCloudStart"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_s3eIOSiCloudStart);
#endif

    s3eResult ret = g_Ext.m_s3eIOSiCloudStart(fileName, supportConflictResolution);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_s3eIOSiCloudStart);
#endif

    return ret;
}

void s3eIOSiCloudStop()
{
    IwTrace(IOSICLOUD_VERBOSE, ("calling s3eIOSiCloud[3] func: s3eIOSiCloudStop"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_s3eIOSiCloudStop);
#endif

    g_Ext.m_s3eIOSiCloudStop();

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_s3eIOSiCloudStop);
#endif

    return;
}

void s3eIOSiCloudTick()
{
    IwTrace(IOSICLOUD_VERBOSE, ("calling s3eIOSiCloud[4] func: s3eIOSiCloudTick"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_s3eIOSiCloudTick);
#endif

    g_Ext.m_s3eIOSiCloudTick();

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_s3eIOSiCloudTick);
#endif

    return;
}

s3eResult s3eIOSiCloudWrite(const void* data, int32 dataSize)
{
    IwTrace(IOSICLOUD_VERBOSE, ("calling s3eIOSiCloud[5] func: s3eIOSiCloudWrite"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_s3eIOSiCloudWrite);
#endif

    s3eResult ret = g_Ext.m_s3eIOSiCloudWrite(data, dataSize);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_s3eIOSiCloudWrite);
#endif

    return ret;
}
