/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
/**
 * Definitions for functions types passed to/from s3eExt interface
 */
typedef  s3eResult(*s3eIOSiCloudRegister_t)(s3eIOSiCloudCallback cbid, s3eCallback fn, void* userData);
typedef  s3eResult(*s3eIOSiCloudUnRegister_t)(s3eIOSiCloudCallback cbid, s3eCallback fn);
typedef  s3eResult(*s3eIOSiCloudStart_t)(const char* fileName, s3eBool supportConflictResolution);
typedef       void(*s3eIOSiCloudStop_t)();
typedef       void(*s3eIOSiCloudTick_t)();
typedef  s3eResult(*s3eIOSiCloudWrite_t)(const void* data, int32 dataSize);

/**
 * struct that gets filled in by s3eIOSiCloudRegister
 */
typedef struct s3eIOSiCloudFuncs
{
    s3eIOSiCloudRegister_t m_s3eIOSiCloudRegister;
    s3eIOSiCloudUnRegister_t m_s3eIOSiCloudUnRegister;
    s3eIOSiCloudStart_t m_s3eIOSiCloudStart;
    s3eIOSiCloudStop_t m_s3eIOSiCloudStop;
    s3eIOSiCloudTick_t m_s3eIOSiCloudTick;
    s3eIOSiCloudWrite_t m_s3eIOSiCloudWrite;
} s3eIOSiCloudFuncs;
